/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/keyboard.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.01}>
        <mesh geometry={nodes.keyboard.geometry} material={materials.wireframe} />
        <mesh geometry={nodes.keys.geometry} material={materials.wireframe} />
      </group>
    </group>
  )
}

useGLTF.preload('/keyboard.glb')
