/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/lanyard.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes['cover-vertical'].geometry} material={materials['trnasparente.001']} />
        <mesh geometry={nodes.headband.geometry} material={materials['FABRIC 1_FRONTU3.001']} />
        <mesh geometry={nodes.Hook.geometry} material={materials['Hook.002']} position={[0, -4.12, 0]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} />
        <mesh geometry={nodes.paper.geometry} material={materials['Card.002']} />
        <mesh geometry={nodes.support.geometry} material={materials['Hook.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/lanyard.glb')
