/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/message.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes['envelope-001-a'].geometry} material={materials['Default.003']} />
        <mesh geometry={nodes['gift-card-001-a001'].geometry} material={materials['card.001']} />
        <mesh geometry={nodes.sticker.geometry} material={materials['sticker.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/message.glb')
