/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/monitor.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes['monitor-screen'].geometry} material={materials.Default} />
        <mesh geometry={nodes['monitor-stand'].geometry} material={materials.Default} />
      </group>
    </group>
  )
}

useGLTF.preload('/monitor.glb')
