/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/portfolioBrownLeather.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 0.06]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes['body-close'].geometry} material={materials.Default} />
        <mesh geometry={nodes.brooch_2.geometry} material={materials.Default} />
        <mesh geometry={nodes['brooch-base'].geometry} material={materials.Default} />
        <mesh geometry={nodes['handle_(2)'].geometry} material={materials.Default} />
      </group>
    </group>
  )
}

useGLTF.preload('/portfolioBrownLeather.glb')
