/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/imacKeyboard.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.25, 0]} scale={[4.87, 0.18, 2]}>
        <mesh geometry={nodes.Cube003.geometry} material={materials.Key} />
        <mesh geometry={nodes.Cube003_1.geometry} material={materials.BadanKeyboard} />
        <mesh geometry={nodes.Cube003_2.geometry} material={materials.Laser} />
        <mesh geometry={nodes.Cube003_3.geometry} material={materials.LobangCas} />
        <mesh geometry={nodes.Cube003_4.geometry} material={materials.Hjau} />
        <mesh geometry={nodes.Cube003_5.geometry} material={materials.TextKey} />
      </group>
    </group>
  )
}

useGLTF.preload('/imacKeyboard.glb')
